### PR TITLE
Added ability to parse ISO 6801 string with nanoseconds

### PR DESCRIPTION
**Pull request by fzakaria**
The default Date class in javascript can support parsing a wide variety of ISO date formats -- although this module should probably not aim for such coverage it would be great to at least parse basic ISO dates with nanosecond resolution.

Examples would be: 2017-08-17T17:04:35.160744338Z

Fixes https://github.com/jcgertig/nano-date/issues/1

### CODE REVIEW

**Comment by jcgertig** [comment]
Why did you delete one of my examples?

**Comment by fzakaria** [comment]
@jcgertig seemed like it was un-needed -- all the usage was found in the README.md.
I can revert that part of the change but it seemed like overkill to me.

I'm going to ignore the hound-ci bot for the recommendations since its on the test file?
What do you think of the change.

**Comment by jcgertig** [comment]
I like the change but yes please limit prs to one set of changes. Also yes just fix the missing semicolon rules.

**Comment by jcgertig** [comment]
@fzakaria ??

**Comment by jcgertig** [comment]
You could also add to the constructor a check using 
`const ISO_8601_FULL = /^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(\.\d+)?(([+-]\d\d:\d\d)|Z)?$/i;`
to see if its this format and use the parser to create the date

**Comment by fzakaria** [comment]
Will address it this weekend. Sorry for the delay.

**Comment by fzakaria** [comment]
sorry for the delay.
I've updated it a bit more to undo the example removal.

**Comment by fzakaria** [comment]
That Hound thing is aggressively annoying heh :)

**Comment by jcgertig** [comment]
im going to merge this but then merge my change on top. Here is my change https://github.com/jcgertig/nano-date/commit/0ed786577029dcf759f1849f6d4bec4b9a8547f3

**Comment by jcgertig** [comment]
Just so you know that its not going to be a class method but will be handled by the constructor instead you can check the way the test works in the above commit.

**Pull request merged**
